### ISSUE TITLE
Freeoffice.appimage is not complete

### ISSUE THREAD

**Issue by fadi123go** [area-of-dev/FreeOffice.AppImage#1]
Freeoffice.appimage contains only the word processor component. I think you will need to create an appimage for each component , planmaker and presentations as well. Thanks.

**Comment by AlexWoroschilow** [comment]
Hi, fadi123go, 
it contains all the components, the problem is to start them. There are only one default enterpoint, the AppImage itself. 
However, there are at least to ways it can be done: 

1. if you start it using the command line tools like at the screenshot below:
![image](https://user-images.githubusercontent.com/3255923/148834437-d31767b4-ef3e-4234-af0f-da4aec905b10.png)

you can find more information here:

https://github.com/area-of-dev/FreeOffice.AppImage/blob/master/Makefile

![image](https://user-images.githubusercontent.com/3255923/148835028-7637c555-e4ce-49f2-a174-410dc4b0aab0.png)



2. If you apply the desktop integration of the AppImage. The .desktop file has more than one enterpoint, you will find all the options in your main menu (kde or gnome)
![image](https://user-images.githubusercontent.com/3255923/148834131-8b5c5e7c-3b0a-446c-b08e-23ea5fea0faa.png)

![image](https://user-images.githubusercontent.com/3255923/148834746-425952c7-59fd-44b4-8373-8d2c5f995866.png)

![image](https://user-images.githubusercontent.com/3255923/148834806-a7147890-e8a5-4751-9323-ccf8474db86c.png)
